# Generated by Django 3.0.7 on 2020-06-30 12:00

import autoslug.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django_ymap.fields
import foreign_country.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заголовок документа',
                'verbose_name_plural': 'Заголовки документов',
            },
        ),
        migrations.CreateModel(
            name='PersonTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заголовок лица',
                'verbose_name_plural': 'Заголовки лиц',
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Текст')),
                ('icon', models.FileField(upload_to=foreign_country.models.Pipeline.get_file_path, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=foreign_country.models.get_default_visa_title, max_length=200, verbose_name='Название')),
                ('title_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в В.П.')),
                ('title_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в Д.П.')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=220, null=True, populate_from='title', unique='True', verbose_name='Ссылка')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(default='Скоро здесь будет статья', verbose_name='Текст')),
                ('duration_validity', models.CharField(default='до лет', max_length=50, verbose_name='Срок действия')),
                ('duration_registration', models.CharField(default='от дня', max_length=50, verbose_name='Срок оформления')),
                ('price', models.CharField(default='от', max_length=50, verbose_name='Цена')),
                ('icon', models.FileField(default='flags/empty-flag.svg', upload_to=foreign_country.models.Visa.get_file_path_icon, verbose_name='Иконка')),
                ('photo', models.ImageField(blank=True, default='visa_photo/visa_photo_default.jpg', upload_to=foreign_country.models.Visa.get_file_path_photo, verbose_name='Фото для заголовка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisaRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('city_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город в П.П.')),
                ('subdivision', models.CharField(blank=True, max_length=20, null=True, verbose_name='Регион iso code')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('coordinates', django_ymap.fields.YmapCoord(max_length=200, verbose_name='Координаты')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=200, verbose_name='Почта')),
                ('website', models.CharField(blank=True, max_length=200, verbose_name='Сайт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foreign_country.Visa')),
            ],
            options={
                'verbose_name': 'Представитель',
                'verbose_name_plural': 'Представители',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisaPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foreign_country.Pipeline', verbose_name='Этап работы')),
                ('visa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foreign_country.Visa', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Этап работы',
                'verbose_name_plural': 'Этапы работы',
                'ordering': ['pipeline_order'],
            },
        ),
        migrations.CreateModel(
            name='VisaPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_1', models.ImageField(default=None, upload_to=foreign_country.models.VisaPhoto.get_file_path, verbose_name='Фото 1')),
                ('note_1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись для фото 1')),
                ('photo_2', models.ImageField(default=None, upload_to=foreign_country.models.VisaPhoto.get_file_path, verbose_name='Фото 2')),
                ('note_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись для фото 2')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foreign_country.Visa')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='VisaPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, null=True, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('person_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign_country.PersonTitle', verbose_name='Лицо')),
                ('visa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign_country.Visa', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisaDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=400, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('document_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign_country.DocumentTitle', verbose_name='Документ')),
                ('visa_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foreign_country.VisaPerson')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='visa',
            name='pipeline',
            field=models.ManyToManyField(through='foreign_country.VisaPipeline', to='foreign_country.Pipeline'),
        ),
    ]
