# Generated by Django 3.0.7 on 2020-06-30 06:41

import about_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('icon', models.FileField(upload_to=about_page.models.AboutPageFeature.get_file_path, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Мы в цифрах',
                'verbose_name_plural': 'Мы в цифрах',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30, verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'История компании',
                'verbose_name_plural': 'История компании',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisite_1', models.CharField(max_length=200, verbose_name='ИНН')),
                ('requisite_2', models.CharField(max_length=200, verbose_name='КПП')),
                ('requisite_3', models.CharField(max_length=200, verbose_name='БИК')),
                ('requisite_4', models.TextField(max_length=200, verbose_name='Юридический адрес')),
                ('requisite_5', models.TextField(max_length=200, verbose_name='Расчетный счет')),
                ('requisite_6', models.TextField(max_length=200, verbose_name='Корреспондентный счет')),
                ('requisite_file', models.FileField(upload_to=about_page.models.Requisite.get_file_path, verbose_name='Файл с реквизитами')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=100, verbose_name='Youtube ID')),
            ],
            options={
                'verbose_name': 'Видео о нашей работе',
                'verbose_name_plural': 'Видео о нашей работе',
            },
        ),
    ]
