# Generated by Django 3.0.7 on 2020-06-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpagefeature',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
