# Generated by Django 3.0.7 on 2020-06-30 06:41

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, upload_to=feedback.models.FeedbackPhoto.get_file_path, verbose_name='Фото')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default=None, upload_to=feedback.models.FeedbackVideo.get_file_path, verbose_name='Фото')),
                ('youtube_id', models.CharField(max_length=100, verbose_name='Youtube ID')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['order'],
            },
        ),
    ]
