# Generated by Django 3.0.7 on 2020-06-30 06:53

import autoslug.fields
import branch.models
from django.db import migrations, models
import django.db.models.deletion
import django_ymap.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Страна')),
                ('title_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна в Р.П.')),
                ('order', models.PositiveIntegerField(default=0, unique=True, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('subdivision', models.CharField(blank=True, max_length=20, null=True, verbose_name='Регион iso code')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=220, null=True, populate_from='city', unique='True', verbose_name='Ссылка')),
                ('coordinates', django_ymap.fields.YmapCoord(max_length=200, verbose_name='Координаты')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Почта')),
                ('whatsapp', models.CharField(blank=True, max_length=200, verbose_name='WhatsApp')),
                ('instagram_link', models.CharField(default='https://www.instagram.com/', max_length=200, verbose_name='Instagram Ссылка')),
                ('instagram_tag', models.CharField(max_length=200, verbose_name='Instagram Тэг')),
                ('work_hours', models.TextField(default='ПН-ПТ с 9:00 до 20:00<br>СБ-ВС выходной', verbose_name='Режим работы')),
                ('vk', models.CharField(blank=True, max_length=200, null=True, verbose_name='VK')),
                ('photo', models.ImageField(default=None, upload_to=branch.models.Branch.get_file_path, verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('country', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.Country', to_field='order', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['order'],
            },
        ),
    ]
