# Generated by Django 3.0.7 on 2020-06-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0002_callback_detected_or_selected_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='detected_or_selected_city',
            field=models.CharField(max_length=100, verbose_name='Определенный/выбранный город'),
        ),
    ]
