# Generated by Django 3.0.7 on 2020-07-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callback', '0003_auto_20200701_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='detected_or_selected_city',
            field=models.CharField(max_length=100, verbose_name='Определённый город'),
        ),
    ]
