# Generated by Django 3.0.7 on 2020-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishCoursePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена на курсы английского языка',
                'verbose_name_plural': 'Цена на курсы английского языка',
            },
        ),
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200, verbose_name='Город')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('price', models.CharField(max_length=20, verbose_name='Цена от')),
                ('how_long', models.CharField(default='5 дней', max_length=20, verbose_name='Срок выдачи')),
                ('visa_counter', models.PositiveIntegerField(verbose_name='Выдано виз')),
                ('photo', models.ImageField(default=None, upload_to='popular_destination_photo', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Популярное направление',
                'verbose_name_plural': 'Популярные направления',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('job', models.CharField(max_length=100, verbose_name='Должность')),
                ('quote', models.CharField(max_length=300, verbose_name='Цитата')),
                ('photo', models.ImageField(default=None, upload_to='staff_photo', verbose_name='Фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Наша команда',
                'verbose_name_plural': 'Наша команда',
                'ordering': ['order'],
            },
        ),
    ]
