# Generated by Django 3.0.7 on 2020-06-30 13:29

from django.db import migrations, models
import index_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Копирайт',
                'verbose_name_plural': 'Копирайт',
            },
        ),
        migrations.AlterField(
            model_name='englishcourseprice',
            name='price',
            field=models.CharField(max_length=30, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=models.ImageField(default=None, upload_to=index_page.models.Staff.get_file_path, verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='quote',
            field=models.TextField(verbose_name='Цитата'),
        ),
    ]
