# Generated by Django 3.0.7 on 2020-06-30 13:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0002_auto_20200630_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyright',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст'),
        ),
    ]
