# Generated by Django 3.0.7 on 2020-07-04 06:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_page', '0003_auto_20200630_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='populardestination',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, max_length=220, null=True, populate_from='title', unique='True', verbose_name='Ссылка'),
        ),
    ]
